# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: '2.1'
orbs:
  browser-tools: circleci/browser-tools@1.2.3
jobs:
    build:
        docker:
            - image: cimg/node:18.4.0-browsers
              environment:
                  - LANG: ja_JP.UTF-8
                  - LANGUAGE: ja_JP.UTF-8

        working_directory: ~/repo

        steps:
            - checkout
            - browser-tools/install-chrome
            - browser-tools/install-chromedriver
            - run:
                  name: "Install Japanese font"
                  command: |
                    sudo apt update
                    sudo apt install -y fonts-takao-gothic
            - run:
                  name: "Download Firefox Developer Edition"
                  command: |
                      curl -L 'https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=linux64&lang=ja' > firefox.tar.bz2
                      tar xvfj firefox.tar.bz2
            - run:
                  command: make ci
            - store_test_results:
                  path: reports
            - persist_to_workspace:
                  root: tmp/workspace
                  paths:
                      - gossip-site-blocker.*
    deploy:
        docker:
            - image: cimg/go:1.17.1

        working_directory: ~/repo

        steps:
            - checkout
            - attach_workspace:
                  at: tmp/workspace
            - run:
                  name: "Publish Release on GitHub"
                  command: make deploy

workflows:
    version: 2
    build-deploy:
        jobs:
            - build:
                  filters:
                      tags:
                          only: /.*/
            - deploy:
                  context: GitHub
                  requires:
                      - build
                  filters:
                      branches:
                          only:
                              - master
                      tags:
                          only: /.*/
    daily_workflow:
        triggers:
            - schedule:
                  cron: "0 9 * * *" # 18:00 JST
                  filters:
                      branches:
                          only:
                              - master
        jobs:
            - build
